### ISSUE TITLE
Notification feed icons

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo-data#106]
If jdolan/quetoo#487 gets merged, we'll need some icons for the notification feed.

Icons are all 32x32.

List of death types (the weapon icons that already exist look good, but would look much better scaled down half size to 32x32 due to texture filtering):

- [x] Generic death (X icon?)
- [x] Blaster
- [x] Shotgun
- [x] Super Shotgun
- [x] Machinegun
- [x] Grenade Launcher (A custom hand grenade icon is possible too if it'll look better)
- [x] Rocket Launcher
- [x] Hyperblaster
- [x] Lightning Gun
- [x] Railgun
- [x] BFG10K
- [x] Drown
- [x] Slime
- [x] Lava
- [x] Crusher
- [x] Telefrag
- [x] Fall damage
- [x] Suicide
- [x] Explosive (No idea what this is for; it's in the code)
- [x] Hurt (trigger_hurt)
- [x] Hook
- [x] "Act of God" (Don't know what this is for)
- [x] Teamkill (This icon is shown to replace the killer's weapon in the kill feed for teamkills)

List of misc. icons:

- [x] Flag taken (red, blue, green, yellow)
- [x] Flag dropped (red, blue, green, yellow)
- [x] Flag returned (red, blue, green, yellow)
- [x] Flag captured (red, blue, green, yellow)

**Comment by Panjoo** [comment]
@kaadmy
Okay I made a bunch of notification icons. They should look alright on both bright and dark backgrounds.
As you can see I left out the square borders that are normally used on the Hud icons because at 32x32 it only takes up space. 
I tried to keep things as simple as possible and easy to see. It certainly took a while to come up with an idea for some of the icons but I think what I got so far gets the job done. Let me know if something doesn't look right or needs adjustment.

http://panjoo.tastyspleen.net/quetoo/uploaded/notifycons.zip

![notifycons](https://user-images.githubusercontent.com/10857572/28250141-7aa02c94-6a62-11e7-8196-6d2c313250e7.png)

**Comment by kaadmy** [comment]
Those all look great, the only ones that stand out are the capture icons (I was thinking just have a capture icon for each of the 4 flags, but this might work better)
Flag dropped might be better with a down arrow overlaid on the flag, similar to the flag return icons.

**Comment by jdolan** [comment]
Those look awesome. So does that font.. someday I'll rewrite the client console with ObjectivelyMVC so that we can use true type fonts..

**Comment by jdolan** [comment]
Oh, and on the flag icons, I think these are cool, but if the capturing team color is too much, we could always just have a white circle around the captured flag for all other teams.

**Comment by kaadmy** [comment]
Is that font Coda?

**Comment by jdolan** [comment]
It looks like Coda, yea.

**Comment by kaadmy** [comment]
Is the shading on the Blaster icon intentional?

**Comment by Panjoo** [comment]
Yep, coda font it is;) The shading on Blaster is intentional because it was a white color, but it can be changed of course. 
Personally I think the flagdrop outline icon is okay, like; the flag's gone all that's left is the contour.
Although adding a down arrow might also work.

> I was thinking just have a capture icon for each of the 4 flags, but this might work better

That's not a bad idea but the way it is now you don't have to look at the colored name pre-fix to see which team captured what flag.
These are icons that you only see when someone actually makes a successful capture. That's an important event, so I figured it should stand out some more. But if it looks really shit in-game I'll change it of course.

**Comment by ptrvrhvn** [comment]
I quickly made the remaining ones. Thoughts? I used to some shading to make them more readable on different colored backgrounds. The white ones kind of require it, the others not so much. They're all from https://thenounproject.com/, which is CC-BY

![icons](https://user-images.githubusercontent.com/28701157/35540833-22107b74-0558-11e8-90cd-5149530c45c9.png)

**Comment by jdolan** [comment]
Act of god fits nicely for telefrags :) @kaadmy Do you still have interest in wiring all of these up? @ptrvrhvn do you mind cutting your new ones up and pushing them to target/default/icons/notifications?

**Comment by ptrvrhvn** [comment]
@jdolan done :)

**Comment by jdolan** [comment]
@kaadmy It looks like you're moving forward in your HUD branch, and you likely have all of the notification icons that you need (?) Can we close this issue out?

**Comment by kaadmy** [comment]
I think this is done now, although if it's easy, 64x64 notifications might be nice to have since 32x32 looks a bit small and won't look crisp on Retina/high-DPI displays.
Feel free to close this out since it's functional now.
