### ISSUE TITLE
Changes to Lighting / Shaders / Textures

### ISSUE THREAD

**Issue by SpineyPete** [jdolan/quetoo-data#108]
This discussion is going to pop up sooner or later so I might as well throw it out here.

With the recent shader updates the maps look different than they used to. Obviously is an issue for mappers whose carefully crafted maps suddenly look different than they intended.

At the there's the question of modernizing the reflectance model, antialiasing of specular highlights, etc. I'm not sure what people think of that, whether they want to freeze the look of the shaders or would prefer to bring them up to date. I've been modifying some of the shader code out of personal interest, and some of it might be used to update the game graphics. Paril and Void have made some changes which I think are for the better. In the end I think a sensible and consistent art direction is more important than having fancy effects. Not sure what everyone else thinks of that.

There's also the question of texture resolution. I'm in favor of higher resolution textures and I know some other are. At the same time there's the question of download size on one hand and consistency on the other. If servers are hosting custom maps it would be nice if the download sizes would be small so you can get into the game quickly. There seem to be some differences of opinion in terms of the density of texture-resolution. Personally, I don't really mind the fact that some maps (e.g. Dark Zone) use significantly higher resolution textures, as long as they are consistent within the map itself.

**Comment by jdolan** [comment]
Good topics, worth of discussion.

I think that, if and when we do decide to modify the lighting model in such a way that maps look different, we should (at least moving forward) have a plan in place for update the existing maps, and some owners identified around who will do that work.

It's not fair for a developer to change something, and then leave it up to the map author to retrofit their finished work to the new tools or new shaders. I'm totally guilty of this, and I'm sorry for the strife I'm sure it's caused Pan.

This sort of topic will be a recurring issue as the game continues to evolve. Most recently, I made changes to quemap around the default lighting parameters for surface lights, which yield overbright lights on many of our existing levels. It's a relatively easy thing to fix, but I pushed that change without having a plan for updating the .map files and recompiling them.

The shaders were also updated, and some of our maps look stark / overbright now as well (Aerowalk is a prime example, the outdoor area on Lava Tomb is another). We should have identified the maps where these changes were dramatic enough to warrant tuning and recompiling, and figured out who would own those updates.

I think the process for these kinds of changes should involve cutting a corresponding branch from `quetoo-data`, and making sure that all of the maps look as good or better than `master` before the code changes are approved and merged.

That's my $0.02 on the _process_ for how we should be addressing these things. Thoughts?

Now, onto the specific items you raised:

 * Lighting model changes: I think that where we can improve the look of the game without throwing our existing assets out the window, we should do that. But, as I mentioned above, I think we need to be a bit more disciplined in rolling those changes out. Separate branches with corresponding data branches would allow us to preview these kinds of things with @Panjoo and other folks. I'd be happy to expand our continuous integration builds to include these branches, so that it's easy for users not familiar with compiling the game to be able to preview or contribute artwork updates, too.

 * Texture resolution: I think we have to find middle ground here, for a number of reasons. Yes, high-res textures look awesome, especially with some of your shader work @ptrvrhvn. No question. But I don't think it's even remotely feasible to retexture all of our maps in 1024 or 2048. I'm guessing @Panjoo feels the same way. I think the only sane thing to do here is consider the completed maps "final" in terms of primary texture assets. As for new maps, I'm fine with using high res assets when they're available. For example, I think _Darker Zone_ looks pretty good, and I'd love to see a few more Quake remakes with Rygel's textures.

I've probably rambled enough on this for now.

**Comment by ptrvrhvn** [comment]
* What would the ideal texture density be for new maps? For the version of Aggressor I'm working on I decided to go for 1024px scaled at 0.125 everywhere.  I remember Unreal Tournament 2003 using primarily 1024px textures 15 years ago so I'm sure that's reasonable. That said, I could settle for 512px which is less of a far cry from the current maps.

* Just an idea I've been having: a lot of maps use the same textures, so rather than bundling those textures per map, the game could come with a couple of texture sets. That would reduce the overall size of the game since the same textures wouldn't be included per-map and would also significantly reduce the size of the map packages. I'm not sure how involved such a change would be.

**Comment by jdolan** [comment]
Creating a couple big `quetoo-001.pk3` or `quetoo-002.pk3` files containing common textures would be fine. We could then update `quemap -zip` to optionally _not_ include assets that are located in other .pk3 files. That way, when you're packaging up a map that uses things from e.g. `quetoo-001.pk3`, it doesn't duplicate them.

**Comment by Panjoo** [comment]
> What would the ideal texture density be for new maps? For the version of Aggressor I'm working on I decided to go for 1024px scaled at 0.125 everywhere. I remember Unreal Tournament 2003 using primarily 1024px textures 15 years ago so I'm sure that's reasonable. 

I've always prefered 512x512. And even if you only have good 256x256 or 256x512 etc. textures you can still make them look much better with the added normalmaps/bumpmaps.

Personally I'm not a fan of 1024 sized textures and then having to scale them down by 4. The combination of the relatively low poly brushwork and high resolution textures makes it look more fake instead of better, at least that's how my eyes see it. 
Besides you don't really see the sharpness when you're playing, only when you stop, stare and zoom in on a texture. I've seen people use highres texture packs for Q2 and Q3 but for the most part it didn't look right; it's like those photo wallpapers of bookshelves. Also I don't think that UT2003 was already using normalmaps which also adds to the total.

Combine 1014x1024 textures (+normalmap) with a higher lightmap scale and the game's going to lose frames that a player with a not so decent system can't miss, not if you want to play like most hardcore quakers do.
Then there's the problem of not always having the textures that you need for your map and if you happen to find some on the web you either have to pay for them or try to make use of a watermarked preview jpeg that needs a lot of editing. If I already have good quality 256 or 512 textures there's no way I could double or quadruple them in size without having to paint and modify them in such a way that I can just as well make new ones from scratch, which I sometimes do if nothing else is to my liking. 
But shit, creating good texture sets (+normals) is a whole project in itself, it'll take months to produce a map and your own special texture set at the same time.

**Comment by ptrvrhvn** [comment]
512 looks fine, imo. I'll just make my textures in 1024, release those as CC and downscale to 512 for the game. I do think the 256 ones look a bit dated though, not gonna lie.

Actually, the reason I'm tending towards the higher level is that I've seen so many godawful retexturing projects, lol. High res textures are easier to screw up.

Here's something which would make me feel good though: if at some point we obtain high resolution versions of the traditional textures, is there an easy way to patch those to the maps? Without having to change all the texture scales and alignment by hand.

**Comment by ptrvrhvn** [comment]
Whoops.

**Comment by void-995** [comment]
Personally, I would prefer not to rescale it back, 1024 kind of fine. It's all mater of resolution of the screen.

If we will bring topic about "how pro players are playing" then it would be better to throw out all textures, make walls grey and floors orange with green player models. Without lighting at all.

Half-Life textures (128x128) were fine too when I played it at 640x480. Now people are doing 8K displays, so it's better to target how will it look at 4K as that's only matter of time when it will become common, which is kind of soon. Half-Life 2 textures (512x512) are looking blurry now and definitely not enough. If we will bring "simplistic level geometry" then you should definitely try to run Unreal Tournament 3 with HOLP3 (hardcore old-school low poly) map pack (which consists of 3 parts), those maps have pretty good texture resolution, but I would not even be against if they will make their resolution 2 times (or even 4 times for 4K displays) bigger in 2017, as it's already 10 years passed and textures looks OK but a bit dated anyway. Not as dated as as 1997-2000 vs 2007, but 2007 vs 2017 is difference anyway. Targeting future with limitations of the past is not the way of progress, you need something future proof.

Also, here is one of my favorite maps from HOLP3 (geometry is simplistic, but textures have pretty high resolution, even if they pretty simplistic as well): https://youtu.be/G8jSwF47Lgs

**Comment by ptrvrhvn** [comment]
As a compromise, we could just ship the game with the medium-res textures, and provide an optional package containing high-res textures for the people who want it? (Could work like jdolan mentioned above with the quetoo-001.pkg etc).

**Comment by void-995** [comment]
And as for low-end PCs there are options to turn texture quality down (r_picmip 1 and r_picmip 2), while let's say realistically - the lowest you should target today is GeForce 8600 GTS which can eat that in no time, especially when we will bring BC1 and BC3 to the tablet (DXT1 and DXT5). And the most low end GPU that people are talking about is GeForce 450 GTS or even GeForce 660 GTS. You need to optimize for low-end, taget for high-end.

P.S. HD kind of DLC sounds good enough. Like base game is super lite to download and get starting and additional pack (which should be asked for if you want it at first launch) for someone who wants it. But 512x512 is bare minimum at the moment anyway from my point of view.

**Comment by kaadmy** [comment]
Nowadays texture resolution isn't a performance loss at all, just video memory, which is a problem with IGPUs and low end mobile GPUs.

If we have the base game use low res (256x256 or 512x512) and have a separate HD texture pack, then our current maps will all need new textures anyway.

Just my two cents.

**Comment by Panjoo** [comment]
Let's forget about the technical side for a moment and the _presumption_ that everyone interested in quetoo will have 26" or sick 4K screens and still get get 500 fps on their vidcards...
For every map that I've made so far I basicly had to scrape together whatever texture I needed to create a certain environment or theme and what I didn't find I had to create myself. (And then I'm not even talking about the normalmaps yet).
One that really knows the process of creating maps from start to finish also knows that the biggest problem is finding the exact textures that you need. I have almost _nothing to work with_ when I'm trying to build maps for quetoo. Even the skyboxes sometimes need to be modified. The only suitable textures that I found so far are from custom Q3 maps or Q2 retexture packs and those use 512 most of the times. Yeah, good luck creating over 300 highres versions of the textures and normalmaps that are already used in the maps.

**Comment by jdolan** [comment]
Agreed, @Panjoo. I think the maps that are complete thus far look great with 512x, and I don't think retexturing them any higher is feasible or honestly even worth the effort.

New maps / Quake1 remakes using Rygel can use 1024 if they are available. Those maps are so low in terms of poly count, that the higher res textures kind of help them blend in with the rest of our maps. As an example, the latest Darker Zone looks pretty much on-point and in-place in Quetoo.

I think 2048 is sort of out of the question, unless we want to make a "tech demo" map or something. I don't want to effectively shit on the great levels that we have just to make one "modern" looking map. It just doesn't make sense. I'm not saying that people can't make higher-res artwork to show off in Quetoo. I'm just saying, I don't _think_ that artwork will have a home in the official release of the game.

Now, back to lighting questions: we have @void-995 's HDR and indirect lighting work sitting in a branch. As far as I'm aware, it's mostly ready to go. I've seen screenshots, and it looks pretty great. From what I gather, the changes required to individual maps is minimal. I think it probably makes sense to create a `quetoo-data` feature branch to begin to bring the maps into alignment with his changes. I will cut the branch today. @void-995 could you push your updated Rage pk3 to this branch at some point today? And / or maybe reply here with a summary of what to look for in tweaking our maps?

**Comment by jdolan** [comment]
So.. 3 years later, we finally have brave-new-world coming to fruition with new lighting and new shaders :D Closing this out.
