### ISSUE TITLE
Broken material definition on Frag Pipe

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#40]
![quetoo001](https://cloud.githubusercontent.com/assets/643118/18536372/d4fe92da-7aca-11e6-87f0-6a4520eedab4.jpg)

**Comment by Panjoo** [comment]
^ This "broken material definition on Frag Pipe" is very strange because even after updating I still don't see it here. I loaded these maps a million times when I was making them and surely I would've noticed the yellow warning.

_material fragpipe/metal14_1
normalmap fragpipe/metal14_1_nm_

The reference in the .mat file looks correct and both textures are present in the pk3, so... no idea.

**Comment by jdolan** [comment]
Okay, so I dug into this a little more and.. wow, WTF?

![screen shot 2016-09-16 at 8 02 25 pm](https://cloud.githubusercontent.com/assets/643118/18604351/8f6fda1e-7c49-11e6-9c21-7fbdef4d4d5c.png)

![screen shot 2016-09-16 at 8 02 44 pm](https://cloud.githubusercontent.com/assets/643118/18604354/92d27dc4-7c49-11e6-81c0-e2e699e96a60.png)

That's the only one. The rest of the textures are fine. Fortunately, GIMP could read it. But even re-exporting it as TGA from GIMP didn't fix the issue. I converted it to PNG. Whatever :|

**Comment by Panjoo** [comment]
I found out that somehow, someone must have converted that TGA to index color mode. What the hell? Should of course be RGB mode. 
![tga-indexcolor](https://cloud.githubusercontent.com/assets/10857572/18604671/8f9e746a-7c7f-11e6-866d-cfa1fb96dcf5.jpg)

**Comment by jdolan** [comment]
Haha! I figured it was something like that. Oh well -- problem solved :)

**Comment by Panjoo** [comment]
Hehe, okay but normally a texture won't look better in 256 colors instead of 24bit tga. Dunno if this influences the normalmap fx. Prolly not.
