### ISSUE TITLE
Fractures: Tiling textures look torn with shaders

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#46]
The error is only visible on the nearest seam, and only from a pretty oblique view angle.

![quetoo004](https://cloud.githubusercontent.com/assets/567688/18806396/20dd12b4-81e0-11e6-8aef-7e9e73b04864.jpg)
![quetoo005](https://cloud.githubusercontent.com/assets/567688/18806397/20f6f918-81e0-11e6-932f-21feb9d365a6.jpg)

**Comment by jdolan** [comment]
Yea, I think this is just a dip in the heightmap around the edges of the texture. Feel free to edit them. The heightmaps are the alpha channel of the normalmap textures.

**Comment by jdolan** [comment]
Alternatively, we could retexture this map with Rygel or something. These textures are rather low-res anyway..

**Comment by Panjoo** [comment]
Yep, just checked the normals of those particular textures and they have a seam on the side that shows when they're tiling.

![nm-badtiling](https://cloud.githubusercontent.com/assets/10857572/18811495/7fbf1eea-82b1-11e6-9546-810fda29fe1b.jpg)

Honestly I think these map textures are fine. Rather low-res but one of the reasons why we're using bumpmaps is to add more details. Actually the normals are higher res so might just be a matter of editing the materials. I have lots of other small things to do first but I'll put it on my todo list.

**Comment by jdolan** [comment]
![quetoo002](https://cloud.githubusercontent.com/assets/643118/19804376/eaffdbc4-9cdb-11e6-9290-cc6e13b3dc48.png)

@Panjoo The normalmaps look great. Really nice job cleaning up the entire map. The new detail brushes look fantastic too (screenshot).

I was a little surprised to see you got rid of the fog, and all of the ice floor. That was the only SURF_SLICK in the entire game. Were you just unhappy with that texture, or do you feel like SURF_SLICK had a negative effect on the gameplay?

**Comment by Panjoo** [comment]
@jdolan
Hey, lol there was no fog to begin with, I just checked every old version of the pk3 that I still have and none of them feature fog, just snow.
As for the snow/ice; it just didn't make any sense. While I was editing the map I had a closer look at the texture usage and it suddenly felt so strange and out of place to have a sheltered basement area that is filled with snow and ice which completely covers every part of the floor. If anything the snow would be covering the 'outside' parts. 
The ice texture was not used in the map and the old snow texture was way too shiny. But I liked the idea of having at least some snowy areas so I made a texture to add patches of frozen snow here and there. IMO this makes it more subtle and believable.
Also surf_slick is bad to have on larger playing areas, it's the same with trying to play on uneven terrain - it makes the map feel awkward. But... but....wait... it might be a nice idea to still flag the new snowy patches as 'slick' (and unflag 'mist') ;-)  You're going to have to do that if you want to try that because I'm very busy with a new little railmap and some extra stuff for Tokays.
(BTW, what do you think of my new hyperblaster barrel? May have to tweak views some more but I think it's mucho bettero.)

**Comment by jdolan** [comment]
Oh, haha. I guess a very, very old version had fog, and that's what I was thinking of ;)

I thought the snow and ice in the inside areas made it feel like an ice box, that's been cold for 100 years, you know? Maybe the bottom-bottom floor (BFG area) could become ice again someday.

New HB barrel is much better! It looks a little small compared to the rest of the model, now. The handle and chamber of the gun are kind of massive. But this is still an improvement. I have not checked the 3rd person view, but the 1st person view does need some adjustment. Up and back, I think.

Can't wait to see more map tweaks like this! The normals and materials look so good now. I love it.

**Comment by jdolan** [comment]
@Panjoo do you plan to adjust the contents or surface flags of the ice patches? I think @Paril posted a gif of grenades interacting with them -- perhaps they are not all `CONTENTS_MIST`?

The best option might be to make them `CONTENTS_SOLID`, but then ramp their vertical surfaces so that grenades slide / jump up over them. And that way, they could also be `SURF_SLICK`. Just a thought.

Otherwise, if you're satisfied with Fractures, feel free to close this one out.

**Comment by Panjoo** [comment]
> The best option might be to make them CONTENTS_SOLID, but then ramp their vertical surfaces so that grenades slide / jump up over them. And that way, they could also be SURF_SLICK. Just a thought.

Thought about this too, but ramping any rotated and non-rectangle brush is a recipe for bad brushed.
It's so hard to properly align a partly transparent decal texture without having parts of it cropped at the sides. All the snowpatches are made out of one texture you know.
What I'm thinking is to set them all as mist but maybe cut up some underlaying floor brushes (roughly the same shape as the snow) and make those surf_slick.

**Comment by jdolan** [comment]
👍

**Comment by Panjoo** [comment]
Updated Fractures - I call this map done*. Commit [83f98ea](https://github.com/jdolan/quetoo-data/commit/83f98ea3418447bb1e5e307fd705ecf8e937938a)

*For now :zipper_mouth_face:
