### ISSUE TITLE
Fractures: snow patches are solid

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#56]
https://gfycat.com/UntriedFlashyFlicker

Maybe they should be detail or mist or something so that stuff doesn't slide off of it?

**Comment by Panjoo** [comment]
The decals are set as detail and mist. Normally a brush set as mist must have all sides set as mist. But, I can't seem to make it so in quetoo that the decal textures only show from one side (top). Apparently there is no 'backface culling' whatsoever, all faces are drawn. And I've tried every combination of flags you can think of. 
So -with the whole brush as mist- you'll see the backfaces of decals in spec mode. I know that's not a real problem but it does make the decals feel kind of fake when you're flying through the maps looking around.

The current state is this: *see picture
-top of the brush has flags: blend33/blend66/mist (texture: snowpatch)
-other sides use the common/clear texture and are flagged as: nodraw
-whole thing 'made detail'
(I've tried it with caulk but the same happens - it gets drawn from both sides.)

![snowdecals](https://cloud.githubusercontent.com/assets/10857572/19862807/15e02b24-9f92-11e6-841d-baa5a7ef2b48.jpg)

Odd that grenades can bounce of them sides. I mean what are they hitting, the nodraw parts or the side of the mist topface?? I thought nodraw gets totally ignored nomally.
I'll just set all sides as mist and have it shown from the bottom in spec mode, not pretty but grenades should not be bouncing of the decals so I guess one thing outweighs the other in this case.

**Comment by jdolan** [comment]
`CONTENTS_MIST` is a contents flag, and can't be applied (correctly) to just one face. It either applies to the whole brush, or not. If you managed to mix the brush contents somehow in Radiant, you might even see a warning about this in quemap (hopefully).

`SURF_NO_DRAW` is just that -- no *draw*. It doesn't mean that there isn't still a clipping plane there.

`CONTENTS_MIST` on the whole brush, and `SURF_NO_DRAW` or even `SURF_SKIP` (caulk) on the sides is the way to go. If there are still collisions with grenades or other objects, then that's a bug and that's on me.

By the way, the back faces are drawn because setting `SURF_BLEND_*` on any surface of a brush turns that brush into `CONTENTS_WINDOW`, and so it's behaving just like any other transparent volume -- the faces are effectively double-sided.

**Comment by Paril** [comment]
It's probably because the sides aren't mist, yeah.

**Comment by Panjoo** [comment]
I understand that you should use mist on all sides, but the confusing part is that at one point I had used blend+mist on the top side and just nodraw on the rest and the snowy faces became one sided faces. Only problem -as it turned out- was that the sides are then clipping planes.

top face of brush: _blend+mist_ & other sides of brush: _nodraw_  => texture becomes one-sided
top face of brush: _blend+mist_ & other sides of brush: _nodraw+mist_ => texture becomes double-sided

As if setting mist also affects the culling. Anyway I'll just change the flags, double-sided decals it is then;)

**Comment by Panjoo** [comment]
Updated Fractures - I call this map done*. Commit [83f98ea](https://github.com/jdolan/quetoo-data/commit/83f98ea3418447bb1e5e307fd705ecf8e937938a)

*For now :zipper_mouth_face:
