### ISSUE TITLE
OBJ models aren't welded properly (?)

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#57]
This issue is specific to the OBJ models. They do not appear to be welded, at least on the main edges.

The new shell code in gl-types uses vertex + (normal * offset) to produce clean shell effects (see old: http://i.imgur.com/hE5Yhri.jpg new: http://i.imgur.com/xYmpFEY.jpg). This effect looks great on MD3, but for some reason the OBJ models appear to have discontinuous connections (see http://i.imgur.com/1NaInva.jpg). Generally this occurs if the models aren't welded, but it's also possible that it's got to do with how the code loads and sets up the model.

Just to see, I had the code manually calculate the normals for every vertex by averaging all of the faces a vertex is a part of - the normals were identical to the ones in the file, leading me to believe that this is an issue with the model and not the code.

**Comment by jdolan** [comment]
The only models that are eligible for this effect (in practice) are the weapons (including the hand grenade). So while ideally, all of them would get fixed up, we can prioritize to this list:

- [ ] models/weapons/bfg/tris.obj
- [ ] models/weapons/blaster/tris.obj
- [ ] models/weapons/grenadelauncher/tris.obj
- [ ] models/weapons/hyperblaster/tris.obj
- [ ] models/weapons/lightning/tris.obj
- [ ] models/weapons/machinegun/tris.obj
- [ ] models/weapons/railgun/tris.obj
- [ ] models/weapons/rocketlauncher/tris.obj
- [ ] models/weapons/shotgun/tris.obj
- [ ] models/weapons/supershotgun/tris.obj

Remaining .obj models:

- [ ] models/armor/shard/tris.obj
- [ ] models/gibs/gib_1/tris.obj
- [ ] models/gibs/gib_2/tris.obj
- [ ] models/gibs/gib_3/tris.obj
- [ ] models/health/large/tris.obj
- [ ] models/health/medium/tris.obj
- [ ] models/health/mega/tris.obj
- [ ] models/health/small/tris.obj
- [ ] models/powerups/adren/tris.obj
- [ ] models/powerups/quad/tris.obj

**Comment by Panjoo** [comment]
What should happen with those models? If I just weld all vertices the models are going to look horrible, because welding results in a phong-shading effect. This is great for player models and stuff but sometimes you want parts of a weapon to remain sharp edged, to get some definition going. Weld everything and the whole model will look like an organic shaped lump. 
Just convert to md3 then?

**Comment by Paril** [comment]
How bad do they look if they are welded? The alternative is that certain models use a special welded version for shell effects, but that seems a bit overkill for what we're trying to accomplish.. besides, we use per-pixel lighting for the models, the phong shading effect thing only really matters if we're talking about a vertex-shaded model.

**Comment by jdolan** [comment]
@Paril Maybe call out one that looks particularly funky now, so that Pan can try either welding or converting to md3, and we can figure out where to go from there?

**Comment by Paril** [comment]
Only the weapon models are affected, in theory, since those have shell effects applied to them. Blaster is probably most noticable because it has tiny bits at the top.

**Comment by Panjoo** [comment]
![phongweld](https://cloud.githubusercontent.com/assets/10857572/20237852/2d5f4924-a8de-11e6-9dd0-1b7718b68de1.gif)

I just tried it on the RL and I don't like the result. I already knew how this was going to look because that's why I only unwelded the edges that I wanted to keep. I haven't looked at the Blaster yet, but I didn't make that model so I don't know if things are welded or not.
I was content with the current models and the old shell effects and I don't feel like making all weapons look less appealing for this. Now I could just try to weld the small top bits of the Blaster and see if that helps, or otherwise convert all models to md3 (but I don't know if that would make a difference without welding?)

**Comment by jdolan** [comment]
Heh, I kind of like the rounded edges and phong shading ^^

I think @Paril was annoyed with how the previous shell effect was drawn, because the shell would sometimes clip through the model in odd ways. I don't disagree, but it's also not a high priority in my opinion.

Here are what the current models look like with the new shell effect. I guess we have to decide if the shell is a significant enough improvement on the player model, to warrant fixing the weapons that look particularly bad with it. If you ask me, only the blaster and MG look strange, and only the iron sights, really.

![quetoo013 png](https://cloud.githubusercontent.com/assets/643118/20238015/8becf5ba-a8af-11e6-9223-fd09c4c588f8.jpg)
![quetoo014 png](https://cloud.githubusercontent.com/assets/643118/20238016/8bee85e2-a8af-11e6-8f30-ce596141a1d5.jpg)
![quetoo015 png](https://cloud.githubusercontent.com/assets/643118/20238017/8bf0fb42-a8af-11e6-8673-662c05d5bf35.jpg)
![quetoo016 png](https://cloud.githubusercontent.com/assets/643118/20238018/8bf32246-a8af-11e6-9046-6c5a18911d38.jpg)
![quetoo017 png](https://cloud.githubusercontent.com/assets/643118/20238019/8bf4e608-a8af-11e6-9d4c-f6701786e089.jpg)
![quetoo018 png](https://cloud.githubusercontent.com/assets/643118/20238020/8bf5f502-a8af-11e6-8654-8312d4717ba0.jpg)
![quetoo019 png](https://cloud.githubusercontent.com/assets/643118/20238021/8bfb0d08-a8af-11e6-844d-7b86f2932623.jpg)
![quetoo020 png](https://cloud.githubusercontent.com/assets/643118/20238023/8bff63a8-a8af-11e6-9d01-14f61c8b9eb2.jpg)
![quetoo021 png](https://cloud.githubusercontent.com/assets/643118/20238022/8bfee022-a8af-11e6-8e4e-2bc2f255120b.jpg)
![quetoo023 png](https://cloud.githubusercontent.com/assets/643118/20238024/8c0115fe-a8af-11e6-9d9e-7e7fadaa6e8f.jpg)

**Comment by jdolan** [comment]
@Paril What do you think? Is it worth trying to tinker with the models to salvage the new effect? I do like the effect, but I also want to make the most of Pan's available time. Maybe @kaadmy could tweak the models, so that Pan can remain focused on the maps?

**Comment by Paril** [comment]
I can fix this entirely in code without affecting the look of the models or Pan's time, no problem. I will have the game consider obj models a little special and generate a second set of geometry purely for shell -  best of both worlds

**Comment by jdolan** [comment]
@Panjoo we'll pursue a code fix for this. We have a couple paths to try. Closing this out! :)

**Comment by Panjoo** [comment]
There are some weapons that could use a little more tweaking as to vertex welding. The barrel of the SSG for example.

![ssg](https://cloud.githubusercontent.com/assets/10857572/20238384/7ab10788-a8ea-11e6-9017-810f71826c66.jpg)

But on the other hand weapons that have more straight lines like the RL, Hyper and BFG should not have all edges welded IMO. 
You may like the "phong" effect but isn't it strange that something that looks like phong shading happens with per-pixel lighting at all? Paril said the phong shading thing isn't relevant. 

> ... or otherwise convert all models to md3 (but I don't know if that would make a difference without welding?)

Can someone please answer this for me? Just straight forward converting to md3 is no trouble at all, but the file sizes get bigger.

**Comment by Paril** [comment]
I was wrong, I misinterpreted what you were saying. The edges will indeed interpolate the light across edges like you were talking about, resulting in light "bleed" in vertices that are connected because of the normal (for instance, in the case of a right angle, the corner angle will be pointing outwards/inwards at a 45 degree angle instead of either straight up or straight left).

So, the way I see it, we have a few fixes we can try:
* reduce shell size on weapon model (I am applying this on master branch, makes the issue less subtle)
* use old "shell scale" effect on .obj models only
* introduce a new "light normal map" texture that lets the artist specify how light bounces off of normals independent of the normal of the vertice itself
* use a secondary model (whether it be a "model.shell.obj" file or calculated in the game itself) that is a minified, welded version of the model that can produce a proper shell
* fall back to old shell entirely, but this means that shells on complex models look like garbage with a lot of clipping (and in some cases bits of it aren't even covered by the shell since it scales from the center. Consider two boxes laid next to each other with a gap inbetween, the scale would mean that the faces close to the center would have a smaller shell than the ones on the outside)
