### ISSUE TITLE
New gibs

### ISSUE THREAD

**Issue by Arseflute** [jdolan/quetoo-data#75]
@Panjoo These are some gib models I made to run past you.

[gib_1.zip](https://github.com/jdolan/quetoo-data/files/752771/gib_1.zip)
![quetoo018](https://cloud.githubusercontent.com/assets/25470615/22623962/501bedf2-eb3a-11e6-968b-036a9706d60c.png)
![quetoo016](https://cloud.githubusercontent.com/assets/25470615/22623966/5a373990-eb3a-11e6-82ac-9c4dff9f2feb.pn
![quetoo013](https://cloud.githubusercontent.com/assets/25470615/22623969/5e22b886-eb3a-11e6-82a3-3aea5dd6b4c1.png)
g)

**Comment by Arseflute** [comment]
![quetoo016](https://cloud.githubusercontent.com/assets/25470615/22623977/91fad512-eb3a-11e6-9c60-8ad49e7a857b.png)
it left that out for some reason

**Comment by kaadmy** [comment]
They look a little small compared to the current gibs, are they mostly to scale? If `sv_max_clients` is 1, you can use `cg_third_person 1` to go to third person and look at them.

**Comment by Arseflute** [comment]
they are to a realistic scale yes... I cant really make the head and hand as big as the ones in game.. but as far as a scale to player model yes they are close

**Comment by Arseflute** [comment]
would look crazy to have a 50lb head :)

**Comment by Paril** [comment]
Not bad so far! I think we need a few more generic boney/gib bits, though. The more the better!

Also I think the art style of the diffuse map might need to be played with a bit. It looks.. well, very "hyper-realistic" and kind of out of place to our bright cartoon-y gfx.

**Comment by Arseflute** [comment]
just let me know. i can do what ever. if it needs to be mudded up or remodeled im good for either one

**Comment by jdolan** [comment]
Hehe, these are hilarious. Agreed with @Paril's feedback. In my opinion, they are a little "DOOM3," which is to say probably too gritty for our aesthetic. We do want to keep with Quake2's cartoonish style. If these could be made brighter, and a little less gory, I think you'd have a winning ticket. I think the arm could be made more "drumstick-y" (lose the mangled hand, that's just gross ;)), and a few more organ chunks (like the giblets that we have, but maybe a just a hint that one is a heart, one is a liver, etc -- you know, like actual giblets!) The rib cage one is awesome. Love it. I also love having a head-specific giblet. We can update the code so that, when you are gibbed. your view is always tied to that specific gib.

**Comment by kaadmy** [comment]
Maybe brighter red and more red than bone/dirt?
Maybe some bone pieces would be nice, like a chunk of spine.
OpenArena has a heart and some other organs, they look nice there.

**Comment by Panjoo** [comment]
@Arseflute
Hehe nice! I like these gibs and I honestly think they fit, even with the "\m/" hand. 
On the other hand:), making it so that the hand/arm looks more like a piece of bone sticking out of a chunk of flesh it could also be regarded as a leg part.
As for the skins, I agree on the cartoonish style argument, but... I also tend to lean towards adding a bit of good old gore. Personally I wouldn't mind seeing you paint some darker bowels on the torso:P
The skull, although nicely done, would probably fit in better if it was less intact and maybe even just a part of a skull.

Anyway I see some problems with the scale (which is not your fault). We can always easily adjust scale but I rather have them in actual proportion to the other models. 

See this image to gauge, this is how they're scaled compared to say a Shard, which isn't re-scaled by the world.cfg
![gibscale](https://cloud.githubusercontent.com/assets/10857572/22628070/78aa1206-ebcd-11e6-9c7b-8f8f9a50d2ea.png)

Now I suspect this has to do with the presence of world.cfg files in the ..share\default\models\gibs\ folders. For instance gib2 has this in its world.cfg:

```
translate "0.0 0.0 0.0"
scale "6.0 6.0 6.0"
``` 
 ^ this will make the gib 6 times bigger when the game loads them...

If you tested these models from the My Games\Quetoo directory and you didn't also use "blank" world.cfg's (with scale 1.0 1.0 1.0), chances are that you had to make them a lot smaller for them to look right ingame.

I just checked and gib1 has scale "3.0 3.0 3.0" in the world.cfg... so to make it in the right proportion again, the gib1 model should really be scaled up by a factor of 3.
Gib2 has scale "6.0 6.0 6.0" so the gib2 model should be scaled up by a factor of 6.
Gib3 has scale "9.0 9.0 9.0", so the gib3 model should be scaled up by a factor of 9 even.

Soon as you've done so, (the gibs will look huge now but only ingame) we can then remove the world.cfg's from the gibs folders or make them all have "scale 1.0 1.0 1.0".
Also the model origins should be put at the center (0,0,0), for instance right now you can only shoot the torso if you hit it from one side.
And you'll probably want to save the skins as 24bit tga, without alpha channel. I'm not 100% sure but on some models having a white (blank) alpha caused visible glitches.

--
@jdolan, @Arseflute,
I see a problem with the "randomness" of the gib spawning. Sometimes the same gib gets used twice for one dead body and you suddenly have two torsos or heads.
This can probably be solved by changing code so that it doesn't spawn the same gib twice, but it might be a be better idea to design the gibs so that you end up with halfs or smaller parts. Say just a part of the current torso and a part of the skull.
I know it's always more work than it sounds so at this point I'd say upscale them and make sure they sit nicely at the center of the axes.

**Comment by WickedShell** [comment]
@panjoo: What if we just role a 40% chance of a head gib, a torso gib, arm,
arm, and then you have however many gibs make it through the 40% chance (or
whatever number feels right) without any duplicates. It's pretty
straightforward from the code side.

Although at that point multiple options would be interesting...

**Comment by Arseflute** [comment]
i was using the base world.cfg of gib1, so i need to probably go set the scale on that to 1.0 around the board, and resize the model accordingly. just to for my OCD sake ;).. im not exactly sure what you mean by cartoonish? and i did originally have some intestines on the torso model, but they looked cheesy as i need to update my subscription to photoshop ;) looked more like a blob of fleshtone snakes than guts lol

**Comment by Panjoo** [comment]
I was refering to what Paril and Jay were saying: 

> In my opinion, they are a little "DOOM3," which is to say probably too gritty for our aesthetic. We do want to keep with Quake2's cartoonish style.

In other words, as long as one can tell what it's supposed to represent (flesh, bone, organs) it doesn't have to be all too realistic. The problem with very small details is that it can make it feel like other things are lacking. Otherwise there should be even more body parts and bits of clothing and whatnot.

@WickedShell - I'd have to see that in action first:) I've no idea if the gibs are picked at random now, but as you already said there are probably more options for this.

**Comment by Arseflute** [comment]
ahh ok i gotcha, alright, im gonna rework them and post again after complete

**Comment by jdolan** [comment]
The giblets are currently randomized, @Panjoo. The player view is arbitrarily bound to one of the giblets (might be gib1, gib2 or gib3). If we have a designated "head" giblet, we'll adjust the code to always bind the player's view to that giblet. That way, other players can identify and knock your head around for fun while you watch.

@Arseflute noticed last night that `misc_lava_ball` actually uses `gib1`. When these giblets are ready, there'll be a minor task to copy the old giblet model to `models/misc/lavaball.obj` and update the code accordingly.

**Comment by WickedShell** [comment]
@jdolan: Or we could have head giblets for lava balls... That could be
kinda cool :)

**Comment by Arseflute** [comment]
ok is this a little more fitting? 
![image](https://cloud.githubusercontent.com/assets/25470615/22856535/283499b6-f061-11e6-94b0-941ff711f268.png)
![quetoo016](https://cloud.githubusercontent.com/assets/25470615/22856537/3af4631a-f061-11e6-9397-7956fc8b264f.png)
![quetoo017](https://cloud.githubusercontent.com/assets/25470615/22856538/3afa6ecc-f061-11e6-8cc8-4f4261f4c19d.png)
![quetoo018](https://cloud.githubusercontent.com/assets/25470615/22856539/3afb0166-f061-11e6-87cb-d1edd2cd4422.png)

**Comment by jdolan** [comment]
Haha, oh man.. that head cracks me up.

**Comment by Arseflute** [comment]
that was the idea wasnt it? :)

**Comment by Panjoo** [comment]
Yes I think that fits better, nice random chunks of bloody goodness. 
And I know what was said about realism but that eye looks a bit too unscathed, with the head almost gone. It should just look more dead like a zombie eye, kind of like this:

![deadeye](https://cloud.githubusercontent.com/assets/10857572/22858516/3f6b697a-f0c0-11e6-8735-cb2963759953.png)

So far 👍

**Comment by Arseflute** [comment]
nice, i think your right
i didnt even think of that, and i should have.. thats way better in my opinion

**Comment by Arseflute** [comment]
@Panjoo can i send you the skin and you work some magic on it?

**Comment by Arseflute** [comment]
i have gimp and i hate that, im about to renew my photoshop subscription but at the moment im without. and im not really familiarized with gimp.. just using what i can. its a pain to make veins and such in. im sure its very possible but im just not on the level of experience with it.

**Comment by Panjoo** [comment]
Yes that's okay mr Buttwhistle, I understand switching tools is a pain. Either try to zip and upload it here or just email it to me.

**Comment by jdolan** [comment]
You can attach up to 10MB here @Arseflute

**Comment by Arseflute** [comment]
i just emailed it to you, for some reason when i try to put the zip file in here it tells me its not supported to try a zip file?? umm ok

**Comment by Panjoo** [comment]
Aight I got the file, thanks. 

Weird that it wouldn't take the zip, let me try ataching your zip here:
[skin.zip](https://github.com/jdolan/quetoo-data/files/769613/skin.zip) <-this is your original skin as a test

hmm see that works, I just dragged it in the text window and it uploaded, lol

**Comment by Arseflute** [comment]
![image](https://cloud.githubusercontent.com/assets/25470615/22865990/736f1038-f13c-11e6-90f1-c9bc28a21262.png)
thats all its giving me, strange...

**Comment by Panjoo** [comment]
Just pushed the updated models, so this is done.

**Comment by Arseflute** [comment]
Awesome, love the texture work you did btw.
