### ISSUE TITLE
CTF techs / runes / powerups?

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#76]
One of my favorite things in the Quake CTF games was the runes/techs that gave you the special abilities - haste, strength, regen and defense. I'd love to bring these back, but we'd need some models for them.

**Comment by jdolan** [comment]
![rune_haste](https://cloud.githubusercontent.com/assets/643118/22748020/b9c10404-edf6-11e6-9e13-ee51f2ebe973.png)
![rune_regen](https://cloud.githubusercontent.com/assets/643118/22748019/b9bce2ac-edf6-11e6-998b-7cbbc809c021.png)
![images](https://cloud.githubusercontent.com/assets/643118/22748021/b9ce334a-edf6-11e6-982c-4f27ac285150.jpg)
![images-1](https://cloud.githubusercontent.com/assets/643118/22748022/b9d06a20-edf6-11e6-8237-1598aa7149c1.jpg)

**Comment by kaadmy** [comment]
Is strength just Quad damage or is or different?

**Comment by jdolan** [comment]
It does 1.5 or 2x damage..

**Comment by Arseflute** [comment]
Model for regen tech, this is just a temp texture tho to get the model in game. Would like to have your feedback on this @Panjoo 
![quetoo034](https://cloud.githubusercontent.com/assets/25470615/22957361/d0b72996-f2f5-11e6-8556-69ece5b2350a.png)
![quetoo035](https://cloud.githubusercontent.com/assets/25470615/22957368/d5b3d82c-f2f5-11e6-8021-772718c8e1e6.png)

**Comment by jdolan** [comment]
This mode is about 10% smaller than the Quad, btw.

**Comment by Panjoo** [comment]
I'm working on mutiple things at once and I also just started with a tech model already.
At first I thought about using a modified quad too but then got the idea to make them more like a _modern techno-powercube_. Using the shape of a rotated ammobox as a base.

![techno](https://cloud.githubusercontent.com/assets/10857572/22983856/c0be98d6-f3a3-11e6-88cb-5c674ea49b2f.gif)

So my idea was to have one model for the techs (how economical) and 4 or 5 unique skins with distinctive colors and signs.

I really _just_ started with building the model (as you can tell from this gif), but I did have stuff planned out for it. That said I don't exactly know yet which look you wish to go for so I guess this is probably something for you guys to decide.

**Comment by jdolan** [comment]
Wait, what? No it's not. You're the creative lead :)

If we go with the box thingus, could we make the primary faces glass and have the "rune" part be inside of it, like a prism? It'd mean that they are each unique models, but I think it'd look really badass.

**Comment by Panjoo** [comment]
I know dude, because you decided to put that title on me :P
I'm fine with making these decisions but I'll never be like "I'm the creative lead and I want it like this, no discussion". Although some things like q2 railgun damage and handgrenades are not really debatable for me,-)

Anyways, @Arseflute has already put some effort into this and he might not have seen Paril 'pinging' me about these models, so I wanted to check what others thought of his tryouts. Personally I think the "wingies" should not be used on the Techs because that'll make them too wide, even with one sided wings. I had the same problem when making the quad and even the logo, those wide wings just kept dictating the scale and taking up much of the available space. These models should stay compact.

Now if you want you could make only the "insets" of the Techs and export to .obj, then I can possibly combine and use those on the inside of my powercubes. I've played lots of Q2 Lithium so I'm familiar with the 5 Runes but I don't know exactly what the 5 symbols represent:

**Strength** = hammer/Quake nail?  /**Resist** = shield  /**Regen** = cross  /**Haste** = bolt  /**Vampire** = drop? maybe simple dracula teeth would look better? V"V

But try to keep these low poly and simple, just like the icons. Same goes for the skin. I'll add the details with glowskins and bumpmaps later on.

--
Although this sort of depends on if we can use transparent parts in a texture. If not I'm going to have to open up the cube).  @jdolan, I don't think we can use glassy parts on models as of yet, I've tried it before on the LG without success and Dragoon's red skin also has alpha parts that don't work.

**Comment by Arseflute** [comment]
oh i just now caught up to this, been playing around with it. actually the pulse thing came to mind as well.
made the cross pulse in the ring. i like the idea of the runes pulsing, it makes them stand out in darker areas a lot better.

**Comment by Paril** [comment]
I'll be honest @Panjoo I hate the idea of having androgynous boxes with different textures. I'm not a fan of the ammo models as-is either personally, but maybe it's just me - they're over-reliant on color cue instead of design. I worry that if the techs go the same route we'll have a similar problem.

The old Q2 techs are immediately recognizable, albeit a little too huge. What if the box was hollow and "contained" the tech power in the center? Like the box would be two pieces (top/bottom) with four side pillars (imagine the pushed in bits are windows) and inside there is a green + for regen, orange nail for strength, etc.

**Comment by Panjoo** [comment]
Oh I hear ya, I have the same feeling about the ammo being all the same and I definitely don't want the Techs to be just like the ammo. It's going to be containers with actual _different_ techpowers inside. Not just different textures. That's what I meant by "opening up the cube".

If you think about it the wingy Q would also be the same for all techs except for the power item inside. So it's the same principle. And I do like what he's made so far but it's that I really like the tech's to be more compact, like a more modern gemstone/powercube. 
And if it somehow turns out to be "androgynous" as you fear, I can always make use of Arseflute's model, he still has to make the rest of the power "insets", if he likes :)

**Comment by jdolan** [comment]
We can absolutely do glass / translucent textures on models. Check out qforcer's visor. It does require enabling blend in the material definition, but that's straightforward.

I like the idea of vampire teeth for the vamp model. Cheeky, but effective. Very Quetoo.

Okay, so it sounds like we have some consensus that Pan's powercube concept, with "windows", probably some unique coloring, and unique rune "charms" inside of it are the path forward?

Is there a straightforward way for @Arseflute to collaborate with you on this @Panjoo, or would you rather create at least one first, and then perhaps have @Arseflute work with those assets to create some of the others?

**Comment by jdolan** [comment]
Thanks for the heads-up on the Dragoon CTF skins, btw. Those were weird. It's almost like they were meant to be additional layers over the default skin -- so that's what I did.

**Comment by Panjoo** [comment]
Ah cool! Yes I'd like to give the powercube design a try first.
The ideas are all still simmering in my mind so gimme some time to see if this could be something. I'm going to do the Haste tech first (w. bolt).
If it completely fails and looks like garbage then we already have something to fall back on. In the meantime arseflute can start creating the other "charms" and mail them to me as .obj files.

**Comment by Arseflute** [comment]
what is your idea for an acceptable tri count for charm, and tri count for entire model?

**Comment by Panjoo** [comment]
Oof hard to say. Maybe around a 100-150 max for the charms, rather have less though. Probably around 500-600 for the entire model. The Quad is close to 500.

**Comment by Arseflute** [comment]
that seems pretty doable really, i was just messing around with it. i dont think that should be a problem at all

**Comment by Paril** [comment]
There will only ever be a max of 5 on screen at once, and even that is an extremely rare scenario, so yeah probably don't go past 600.

> and mail them to me as .obj files.

I like the idea of physically mailing a USB stick with .obj files on them. It cracks me up.

**Comment by Arseflute** [comment]
Wait that's not how your supposed to do it?

**Comment by Panjoo** [comment]
^  \o/ :)

---
Since you also asked about tris count for the entire model, and just to make sure; you don't need to do an entire model just those inner charms. And no skin mapping yet, I'll have to do that afterwards with the complete model.

Thinking about this some more, the _total_ polycount will be a lot lower than what I guessed. 
The container box is around 75 and is not going to be much more complex than it is. Add to this the charms of around 150 max and we total to about ~250.
So basicly that means that in theory you'd have some more polys to use on the charms but like I said try to keep it simple and to the point. Otherwise I'll have to redo things myself afterwards.

**Comment by Arseflute** [comment]
Oh yeah I know, I just made a test run last night and my guess was around 100 tris for the charms, I really don't think it would take that many tho. Can you give me a list of what you guys decided for the charms

**Comment by Panjoo** [comment]
> Paril: Basically what you'd do for the case of the tech is have the container and the outside be part of the main diffuse map and the window in the diffuse map would be completely transparent, then you have a secondary texture (like rune_window.tga) as a second stage with blending.

Been trying to get this to work but this description not very clear to me. What I get from this is I have to make the actual skin with both components (container + windows) in the same image, just like a I normally would with any skin. And then on this image, I only make the window part completely transparent. I tried to do this by creating an alpha channel as shown in this pic, the black area should be the window:

![alphatech](https://cloud.githubusercontent.com/assets/10857572/23092391/30253bc6-f5ca-11e6-8c27-1b16a76abdd6.jpg)
^ Saved as 32bit tga. I then made a glass texture without alpha to be used as a second stage blend.

```
{
	material #models/techs/strength/skin
	bump 1.5
	hardness 2.0
	parallax 0.0
	specular 2.0
	{
		texture #models/techs/strength/glass
		blend GL_ONE GL_ONE
		mesh_color
	}
}
```

But this doesn't do anything, the thing refuses to be transparent. What am I doing wrong? Already tried without the normalmap but makes no difference.  

> Paril: There's also some new stage parameters that make the stage keep mesh lighting instead of being fullbright.

Where do I find this info? In this test I just use mesh_color, but I obviously like the glass to not be fullbright.

**Comment by Paril** [comment]
mesh_color will cause the stage to use the mesh coloring instead of being fullbright.
In theory that should work; can you send me the zip with the test files so I can play with it?

**Comment by Panjoo** [comment]
^ done.
I'm going to experiment some more with these skins.

**Comment by Arseflute** [comment]
do i need to go ahead and place the charms inside the round winged model?

**Comment by Panjoo** [comment]
Nah, I'm working on something new with the charms, something more sphere-like.
But if it happens to turn out less nice than I have in mind I'll let you know in time.

**Comment by Arseflute** [comment]
Oooo, is it like a glass sphere with charm inside?? That will look bad ass
in my opinion.

**Comment by Panjoo** [comment]
Agreed. But Paril has told me that a model is limited to one diffuse texture for the entire model, so at this point I can't get transparency to work on them skins without making the entire thing transparent.
But what I have so far is starting to look nice too.

**Comment by jdolan** [comment]
I mean.. can't you just have part of the texture use the alpha channel?

**Comment by Panjoo** [comment]
^No, as I mentioned above, that was the problem. It just can't become partially transparent like it can on playermodel skins.

BTW I've already pushed the new Techs, they look even better when they're spinning. 
Would be nice to eventually give them their own special fx sounds I think.

![prev-techs](https://cloud.githubusercontent.com/assets/10857572/23468543/58c0b1ac-fea1-11e6-865d-7e7552bbc9c5.jpg)

**Comment by jdolan** [comment]
Holy shit, @Panjoo. Those look amazing.

**Comment by Paril** [comment]
Since these are done I'm gonna close this, and open a new ticket for the sounds.
