### ISSUE TITLE
Tokays Towers BFG should alternate with Railgun

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#78]
I really miss having the BFG more readily available on this map. We've play tested the map with 4-8 humans a couple times, and no one has bothered to RJ up to it yet. I'd really love to see it alternate spawn with the Railgun like it does on q2dm2.

**Comment by Panjoo** [comment]
Roger. I need to edit a couple of little things in tokays anyway.

**Comment by jdolan** [comment]
@Panjoo Btw if you idled in Discord, you wouldn't miss out on 8 player Quetoo on your maps! :D

**Comment by Paril** [comment]
Team chain works the same way it does currently yeah? Should be easy :)

@Panjoo you can join through browser without needing to download a thing or even make an account. We'd love to have you more readily available to poke.

**Comment by jdolan** [comment]
It's really sad, but @Panjoo and I have literally never played Quetoo against each other. Isn't that crazy? I bet he'll kick my ass, too.

**Comment by Panjoo** [comment]
Tokays updated.

Yeah, that is pretty crazy when you think about it! But then again for a long time the game wasn't very playable online, for me at least. I'm also like 6 or 7 hours ahead of you so that's sort of inconvenient. I'd have to stay up late and you'd have to start playing pretty early. 
Just checked out discord and registered, btw.

> Paril: We'd love to have you more readily available to poke.

Yeah I bet you would. 
![pokepoke](https://cloud.githubusercontent.com/assets/10857572/22762840/adae1632-ee61-11e6-8233-9e7405435c97.jpg)
